CREATE TABLE Patient (
    PK INT NOT NULL AUTO_INCREMENT,
    ID UUID NOT NULL DEFAULT (RANDOM_UUID()) UNIQUE,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    GENDER VARCHAR(20) NOT NULL,
    BIRTH_DATE DATE,
    PRIMARY KEY(PK));